version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3zh0p1bc2yia"
s3_prefix = "serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"products\""
